package com.googlecode.dummyjdbc.statement.impl;

import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Map;

import com.googlecode.dummyjdbc.statement.PreparedStatementAdapter;

/**
 * Wraps the {@link CsvStatement} as a prepared statement.
 *
 * @author Kai Winter
 */
public class CsvPreparedStatement extends PreparedStatementAdapter {

	private final CsvStatement statement;
	private final String sql;

	private ResultSet currentResultSet;

	/**
	 * Constructs a new {@link CsvPreparedStatement}.
	 *
	 * @param tableResources {@link Map} of table name to CSV file.
	 * @param sql
	 *            the SQL statement.
	 */
	public CsvPreparedStatement(Map<String, File> tableResources, String sql) {
		this.statement = new CsvStatement(tableResources);
		this.sql = sql;
	}

	@Override
	public ResultSet executeQuery() throws SQLException {
		return (currentResultSet = statement.executeQuery(sql));
	}

	@Override
	public ResultSet executeQuery(String sql) throws SQLException {
		return (currentResultSet = statement.executeQuery(sql));
	}

	@Override
	public boolean execute() throws SQLException {
		currentResultSet = statement.executeQuery(sql);
		return true;
	}

	@Override
	public boolean execute(String sql) throws SQLException {
		currentResultSet = statement.executeQuery(sql);
		return true;
	}

	@Override
	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		return execute(sql);
	}

	@Override
	public boolean execute(String sql, String[] columnNames) throws SQLException {
		return execute(sql);
	}

	@Override
	public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
		return execute(sql);
	}

	@Override
	public ResultSet getResultSet() throws SQLException {
		return currentResultSet;
	}
}
